version: '3'

services:
  postgres:
    image: 'postgres:12-alpine'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/